server.port=8081
spring.datasource.url=jdbc:mysql://localhost:8081/bankdb
spring.datasource.username=root
spring.datasource.password=spss

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Optional but safe fix
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect